# Generated by Django 2.0.7 on 2018-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0018_auto_20180823_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='crowdfunding_url',
            field=models.CharField(default='', help_text='The candidate crowdfunding', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='facebook_url',
            field=models.CharField(default='', help_text='The candidate facebook page', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(default='', help_text='The full name of the candidate', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='instagram_url',
            field=models.CharField(default='', help_text='The candidate instagram page', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(help_text='The urn name of the candidate', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='occupation',
            field=models.CharField(default='', help_text='The occupation of the candidate', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='public_email',
            field=models.CharField(default='ricardo@cidadedemocratica.org.br', help_text='The candidate public email', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='twitter_url',
            field=models.CharField(default='', help_text='The candidate facebook page', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='youtube_url',
            field=models.CharField(default='', help_text='The candidate instagram page', max_length=200),
        ),
    ]
