# Generated by Django 2.0.6 on 2018-09-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0019_favoritecandidate'),
        ('ej_candidates', '0019_auto_20180910_1903'),
    ]

    operations = [
    ]
