# Generated by Django 2.0.8 on 2018-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0019_auto_20180910_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='cpf',
            field=models.CharField(default='00000000000', help_text='The candidate cpf', max_length=11),
        ),
    ]
