# Generated by Django 2.0.8 on 2018-09-24 17:45

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0020_candidate_cpf'),
    ]

    operations = [
            UnaccentExtension()
    ]
