# Generated by Django 2.0.8 on 2018-09-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_candidates', '0021_auto_20180924_1745'),
        ('ej_candidates', '0020_merge_20180920_1530'),
    ]

    operations = [
    ]
