# Generated by Django 2.0.6 on 2018-07-04 19:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ej_missions', '0024_mission_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
